intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs += libcrails%lib{crails}
import intf_libs += libcrails-controllers%lib{crails-controllers}
import intf_libs += libcrails-encrypt%lib{crails-encrypt}
import intf_libs += libcrails-http-client%lib{crails-http-client}
import intf_libs += libbacktrace%lib{backtrace}

lib{crails-payment}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: cxx.poptions += -DLIBCRAILS_PAYMENT_STATIC_BUILD
objs{*}: cxx.poptions += -DLIBCRAILS_PAYMENT_SHARED_BUILD

# Export options.
#
lib{crails-payment}:
{
  cxx.export.poptions = "-I$out_root/libcrails-payment/" "-I$src_root/libcrails-payment/"
  cxx.export.libs = $intf_libs
}

liba{crails-payment}: cxx.export.poptions += -DLIBCRAILS_PAYMENT_STATIC
libs{crails-payment}: cxx.export.poptions += -DLIBCRAILS_PAYMENT_SHARED

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{crails-payment}: bin.lib.version = "-$version.project_id"
else
  lib{crails-payment}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libcrails-payment/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
